# Generated by Django 4.2 on 2023-04-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='translation',
            field=models.CharField(default='', max_length=100, verbose_name='Translation'),
            preserve_default=False,
        ),
    ]
