# Generated by Django 4.2 on 2023-04-30 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_words_translation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='words',
            name='gender',
        ),
    ]
